services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linguere-api
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - JWT_SECRET=change_this_secret_in_production
      - JWT_EXPIRES_IN=1d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      # - OPENWEATHER_CITY=Dakar
      # - EXCHANGE_RATE_BASE_CURRENCY=XOF
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      # - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      # - FRONTEND_URL=${FRONTEND_URL}
      # - MAIL_HOST=${MAIL_HOST}
      # - MAIL_PORT=${MAIL_PORT}
      # - MAIL_SECURE=${MAIL_SECURE}
      # - MAIL_USER=${MAIL_USER}
      # - MAIL_PASS=${MAIL_PASS}
      # - MAIL_FROM=${MAIL_FROM}
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - linguere-net

  redis:
    image: redis:7-alpine
    container_name: linguere-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - linguere-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - linguere-net
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - linguere-net
    depends_on:
      - prometheus

networks:
  linguere-net:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data:
